### ISSUE TITLE
Determine a more suitable name for st:option property

### ISSUE THREAD

**Issue by justinwb** [shapetrees/specification#48]
> The `st:option` property in a containing shapetree identifies unmanaged resource types permitted beyond those in-scope.

Need a more specific name than `st:option`.  Some ideas:

* `st:alsoAllow`
* `st:allow`
* `st:permit`
* `st:alsoPermit`

_Raised in #46 by @ericprud_

**Comment by ericprud** [comment]
+1 to `st:alsoAllow`
