### ISSUE TITLE
reconsider combining 2 steps of planing into one step

### ISSUE THREAD

**Issue by elf-pavlik** [shapetrees/specification#6]
as discussed during the call, it may not be needed to combine
* create container
* assign shapetree to manage it

we need them separate anyways to assign shapetrees to existing containers.

**Comment by joshdcollins** [comment]
@elf-pavlik Can you please review the changes (still in progress) on the spec here: https://github.com/shapetrees/specification/blob/doc-updates/spec.bs

I believe this does a better job of breaking down each logical operation of shape trees into their lower level steps.

Does this get us closer to addressing your concern?  If not, let's discuss further.  Thanks!

**Comment by elf-pavlik** [comment]
Yes, thank you!
