### ISSUE TITLE
Tree prefix collision 

### ISSUE THREAD

**Issue by pietercolpaert** [shapetrees/specification#7]
Dear @justinwb and @ericprud,

With great interest I learned about the shapetrees specification. I love the idea of footprints and believe this specification will have quite an influence on the Solid ecosystem.

One minor remark is that for the past 2 years I’ve been working on the TREE specification (https://github.com/TREEcg/specification), which has the same preferred prefix you just chose for this spec. This of course would not have been a big issue if the projects were in different domains. However, we seem to use similar predicates, and while the projects solve different problems, I do believe at some point they might be used together (e.g., we also foresee TREE relations between pages of LDP Containers as an alternative to ordered pagination).
 
In order to omit possible confusion in the future, would you be willing to consider a different preferred prefix for your vocabulary? `st:` or `sht:` for instance?

Thank you in advance,

Pieter

**Comment by justinwb** [comment]
@pietercolpaert Thanks for raising this and glad to hear you're interested in this work! Apologies for the prefix-crashing. We're looking at some alternative options. Will follow-up here with an update soon.

**Comment by pietercolpaert** [comment]
Thank you very much!

**Comment by justinwb** [comment]
@pietercolpaert we decided to go with `st:`. We'll leave this issue open until things are updated 🙂

**Comment by justinwb** [comment]
@pietercolpaert We've officially updated to `st:`, which you can see reflected in the [source](https://github.com/shapetrees/specification/spec.bs) and [rendered](https://shapetrees.github.io/specification/spec) versions of the specification document. There are some errant references in the primer document, but only because it's due for revision next week, following this week's spec updates. I'll close this issue out - thanks again for raising!

**Comment by pietercolpaert** [comment]
And thank you for your very prompt replies and actions!

**Comment by pietercolpaert** [comment]
> @pietercolpaert We've officially updated to `st:`, which you can see reflected in the [source](https://github.com/shapetrees/specification/spec.bs) and [rendered](https://shapetrees.github.io/specification/spec) versions of the specification document. There are some errant references in the primer document, but only because it's due for revision next week, following this week's spec updates. I'll close this issue out - thanks again for raising!

Reading through the specs (looking into a pilot to combine shapetrees with hypermedia trees) I see the primer still uses `tree:` atm. Spec documents are updated to use `st:`!

**Comment by justinwb** [comment]
Hi @pietercolpaert - that's an artifact as we've been focused on the spec doc and still haven't circled back to update the primer docs yet. We'll get that cleaned up.
